# Sử dụng Nginx chính thức
FROM nginx

WORKDIR /usr/share/nginx
# Sao chép cấu hình Nginx vào container
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Mở cổng cho Nginx
EXPOSE 80
CMD [ "sh", "-c", "nginx -g 'daemon off;'" ]
